package com.ftn.sbnz.rules;

import com.ftn.sbnz.model.ScoredItem;
import com.ftn.sbnz.model.SubscaleAverage;
import com.ftn.sbnz.model.DependsOn;
import java.util.List;


rule "Calculate subscale average per family"
    salience -10
when
    $si: ScoredItem($familyId: familyId, $subscale: subscale)
    not SubscaleAverage(familyId == $familyId, subscale == $subscale)
    accumulate(
        ScoredItem(familyId == $familyId, subscale == $subscale, $value: value);
        $avg: average($value)
    )
    $items: List(size > 0) from collect(
            ScoredItem(familyId == $familyId, subscale == $subscale)
    )
then
    SubscaleAverage avg = new SubscaleAverage($familyId, $subscale, $avg.doubleValue());
    insert(avg);
    for (Object item : $items) {
        insert(new DependsOn(avg, item));
    }
end